import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";
import PageLayout from "@/components/designsystem/PageLayout";
import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <body
        className={cn(
          "min-h-screen font-sans antialiased bg-black",
          fontSans.variable
        )}
      >
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
